$(function(){ 
        $('.btn-1').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#home').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
     $(function(){ 
        $('.btn-2').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#tatuagens').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
     $(function(){ 
        $('.btn-3').click(function(){
         $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#piercings').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-4').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#agendar').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-5').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#localizacao').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-6').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#faleconosco').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-7').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#modelos').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-8').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#tatuadores').hide()
            .delay('800')
            .fadeIn("slow");
        });
      });
      $(function(){ 
        $('.btn-9').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#instalacoes').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-10').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#desenvolvimento').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-11').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#sobre').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-12').click(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);
          $('#politica').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
      $(function(){ 
        $('.btn-13').click(function(){
          /*$('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          $('#suporte').fadeOut(800);*/
          limpar(); 
          $('#suporte').hide()
            .delay('800')
            .fadeIn("slow");
        });
      }); 
    function limpar(){
    $(function(){
          $('.sub-menu-mob').fadeOut(200);
          $('.btn-sub-menu-sel').hide();
          $('.btn-sub-menu').show();
          $('#home').fadeOut(800);
          $('#tatuagens').fadeOut(800);
          $('#piercings').fadeOut(800);
          $('#agendar').fadeOut(800);
          $('#localizacao').fadeOut(800);
          $('#faleconosco').fadeOut(800);
          $('#modelos').fadeOut(800);
          $('#tatuadores').fadeOut(800);
          $('#instalacoes').fadeOut(800);
          $('#desenvolvimento').fadeOut(800);
          $('#sobre').fadeOut(800);
          $('#politica').fadeOut(800);
          //$('#suporte').fadeOut(800);
      }); 
      }